### ISSUE TITLE
Error Importing it to Android Studio

### ISSUE THREAD

**Issue by amedina1570** [MacroYau/Blue2Serial#1]
This project has some outdated libraries and some reference errors. At first I change the build.gradle script for the latest libraries that one of them was 'com.afollestad:material-dialogs' and the script had no problems but then a ListCallback error was found while compiling. The error was the following:
- Error:(124, 17) error: method adapter in class Builder cannot be applied to given types; 
  required: ListAdapter,ListCallback
  found: BluetoothDeviceListItemAdapter
  reason: actual and formal argument lists differ in length 

I tried few things like calling the class builder by reference or creating a local object of the function but due to my inexperienced skills I was unable to resolve the root of the problem. Has the author or anyone have some plans to update this project?

**Comment by MacroYau** [comment]
Please update the library version to `0.1.1`. If Android Studio fails to resolve the jCenter repository, please add the following lines to the `build.gradle` file to switch to my Maven repository.

``` Gradle
repositories {
    maven {
        url "http://dl.bintray.com/macroyau/maven"
    }
}
```

**Comment by amedina1570** [comment]
Thank you MacroYau for updating this project, it worked flawlessly. You can now close this issue.
