### ISSUE TITLE
Can I use this to connect two Android phones

### ISSUE THREAD

**Issue by wterreb** [MacroYau/Blue2Serial#11]
Hi  
I'm trying to use this library and example app to connect two paired Android phones.  But each time I click on "Connect"  it just goes "Connecting..." and then "Disconnected"
Is it possible to connect between two Android phone using this library?

**Comment by MacroYau** [comment]
No. You may want to refer to [Google's sample](https://github.com/googlesamples/android-BluetoothChat) for bi-directional connection.
