### ISSUE TITLE
Connecting to multiple bluetooth devices

### ISSUE THREAD

**Issue by pleong1231** [MacroYau/Blue2Serial#14]
Hi,  can this be used to connect to multiple devices?  I am doing a school project and need this info urgently.  I tried with no success.  Can anyone give me some sample code on how to do this?

Thanks in advance!

**Comment by MacroYau** [comment]
I have not tested this with Bluetooth SPP (or Bluetooth Classic in general), but you may try to get some inspirations from another library: https://github.com/arissa34/Android-Multi-Bluetooth-Library

**Comment by pleong1231** [comment]
Thanks for your info!

Can i create multiple instance using your library?  In other words connect
to multiple bluetooth devices?
