### ISSUE TITLE
bluetoothSerial.write not working when called from extended class

### ISSUE THREAD

**Issue by ghost** [MacroYau/Blue2Serial#16]
Hello,

I have my function in MainActivity:

`public void send(String value) {
        String send = value.trim();
        if (send.length() > 0) {
            try {
                bluetoothSerial.write(send);
            } catch(Exception e) {
                e.printStackTrace();
            }
        }
    }`

It's sending well when I call it from this MainActivity.
But, when I call it from my class "LaunchGame" (which is an extended class of MainActivity), it's sending nothing and I have no error...

Someone already had this kind of error ?

**Comment by MacroYau** [comment]
I have not touched the codebase for quite a while, but I believe that only one `BluetoothSerial` instance can be used to access to the Android device's Bluetooth modem at a time.
