### ISSUE TITLE
Unfortunately, Blue2Serial has stoped

### ISSUE THREAD

**Issue by hamidnaghi** [MacroYau/Blue2Serial#5]
Once I upload it in the tablet or android phone then it pops up a dialogue box on the tablet or phone says " Unfortunately, Blue2Serial has stopped". I attached the output log.
It was working before, but I think once Android Studio asked to upgrade, then it's happened after upgrading!
[ScreenShot.pdf](https://github.com/MacroYau/Blue2Serial/files/153868/ScreenShot.pdf)
Please help me to find the issue.

**Comment by MacroYau** [comment]
This appears to be an issue related to the recent Support Library update to v23.2 (though I haven't tested it yet). Try to update it to the latest version as instructed here: http://android-developers.blogspot.hk/2016/02/android-support-library-232.html

Please help report after trying this and I will update the repository later on. Thanks!

**Comment by MacroYau** [comment]
Library version updated to 0.1.3. Please try again with the latest version.

**Comment by hamidnaghi** [comment]
Thank you Macro,

I'll try it

Best regards,
Hamid
