### ISSUE TITLE
onBluetoothSerialWrite & onBluetoothSerialRead - return byte[]?

### ISSUE THREAD

**Issue by CristinaNicolae** [MacroYau/Blue2Serial#6]
Hello. 

**Great library** btw. I don't want to modify your library, I like using it with gradle. 
Can you please make an update so that onBluetoothSerialWrite and onBluetoothSerialRead have a byte[] parameter, instead of String? 

It would help me a lot. I am using bytes processing and by converting them from String some of the bytes get messed up. 

Thank you. 
I think something needs to be changed here:

```
                case MESSAGE_WRITE:
                    byte[] bufferWrite = (byte[]) msg.obj;
                    String messageWrite = new String(bufferWrite);
                    mListener.onBluetoothSerialWrite(messageWrite);
                    break;
                case MESSAGE_READ:
                    byte[] bufferRead = (byte[]) msg.obj;
                    String messageRead = new String(bufferRead);
                    mListener.onBluetoothSerialRead(messageRead);
                    break;
```

This is in **BluetoothSerial.java**

**Comment by MacroYau** [comment]
Thanks for your suggestion! I have just added this feature in the latest v0.1.4 release of this library. You can now try to replace the original `BluetoothSerialListener` interface with the new `BluetoothSerialRawListener` to use the `onBluetoothSerialReadRaw()` and `onBluetoothSerialWriteRaw()` methods.
