### ISSUE TITLE
autoConnect to static device MAC

### ISSUE THREAD

**Issue by SalvatoreAD** [MacroYau/Blue2Serial#7]
Hi, I use this library and It helped me a lot. Is it possibile to auto connect to the device , when the app is open?

**Comment by MacroYau** [comment]
You should be able to implement this using the [`connect(String address)`](https://github.com/MacroYau/Blue2Serial/blob/8768d4af55acfbea2d9c002151f4c00cfca84bcf/library/src/main/java/com/macroyau/blue2serial/BluetoothSerial.java#L114) method in the `BluetoothSerial` class.

**Comment by SalvatoreAD** [comment]
Can you help me?

**Comment by axgdev** [comment]
First of all, MacroYau thanks for the library, it seems to work nicely! @SalvatoreAD, MacroYau already helped you by providing you the method. You should take a look at how the sample app that MacroYau has made. In the `TerminalActivity` class, you could connect directly to Bluetooth if you avoid opening the window of device selection and directly use bluetoothSerial.connect(String address).
