### ISSUE TITLE
Show scanned devices?

### ISSUE THREAD

**Issue by Samyssmile** [MacroYau/Blue2Serial#8]
Hello

This works perfectly if i wanna connect to a paired device. How can i show results new (scanned) devices and conntect to them.

In your example code I found only paired soulution

**Comment by MacroYau** [comment]
Device discovery is currently out of the scope of this library. You may try to follow [this](http://stackoverflow.com/a/10782714) for implementation based on the [`startDiscovery()`](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#startDiscovery%28%29) method in Android API's `BluetoothAdapter` class.
